### ISSUE TITLE
启动App崩溃

### ISSUE THREAD

**Issue by CSGA-KPX** [Hallbin/avalanche-test#1]
系统：8..0.0
机器：LG G7 ThinQ
浏览器：Firefox
WebView实现：Android System WebView
App版本是目前Google Play推送的最新版，早上更新完就挂了。

能正常接收通知，只是点不开

adb日志：
```
03-11 22:22:54.184 12237 12237 E AndroidRuntime: FATAL EXCEPTION: main
03-11 22:22:54.184 12237 12237 E AndroidRuntime: Process: com.avalanche.avalanche, PID: 12237
03-11 22:22:54.184 12237 12237 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.flutter.view.AccessibilityBridge.isAccessibilityEnabled()' on a null object reference
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at io.flutter.view.FlutterView.getAccessibilityNodeProvider(Unknown Source:2)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.createAccessibilityNodeInfoInternal(View.java:7299)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.createAccessibilityNodeInfo(View.java:7289)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:146)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.onInitializeAccessibilityEventInternal(View.java:7241)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.onInitializeAccessibilityEvent(View.java:7229)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:7091)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.sendAccessibilityEventUnchecked(View.java:7076)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.sendAccessibilityEventInternal(View.java:7053)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.sendAccessibilityEvent(View.java:7020)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.onFocusChanged(View.java:6934)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.handleFocusGainInternal(View.java:6631)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.requestFocusNoSearch(View.java:10861)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.requestFocus(View.java:10840)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3278)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3234)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3278)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3234)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3278)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3237)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.requestFocus(View.java:10807)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.requestFocus(View.java:10749)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3562)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.setFlags(View.java:13339)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.view.View.setVisibility(View.java:9416)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.app.Activity.makeVisible(Activity.java:5417)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3884)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2956)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6759)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-11 22:22:54.184 12237 12237 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

**Comment by Hallbin** [comment]
应该是 Flutter dev branch 最新的 commit 造成的问题
等待下次的 dev 版本更新

```
Flutter 1.3.9 • channel dev • https://github.com/flutter/flutter.git
Framework • revision f91df4abe1 (3 days ago) • 2019-03-09 21:19:28 -0500
Engine • revision 4e54bc93ca
Tools • Dart 2.2.1 (build 2.2.1-dev.1.0 2fb6cd9f5f)
```
https://github.com/flutter/flutter/wiki/Bad-Builds
```
v1.3.9
Android crash on FlutterView.getAccessibilityNodeProvider due to NPE (https://github.com/flutter/flutter/issues/29203)
```

**Comment by Hallbin** [comment]
暂时已经采用 1.3.8 的 flutter engine 版本
等待推送之后检查一下是否可以正常运行

**Comment by CSGA-KPX** [comment]
已正常。
